### ISSUE TITLE
Installation issues (from doc)

### ISSUE THREAD

**Issue by BenMGeo** [pygeo/dummydata#1]
Issues with dateutil. In Python, *import dateutil* works. For installation, as proposed in the docs, it doesn't: 

Option 1: PIP - could not satisfy requirement dateutil

    Requirement already satisfied (use --upgrade to upgrade): dummydata in /home/bmueller/anaconda2/lib/python2.7/site-packages/dummydata-0.1.2-py2.7.egg
    Requirement already satisfied (use --upgrade to upgrade): numpy>0.1 in /usr/local/lib/python2.7/dist-packages (from dummydata)
    Requirement already satisfied (use --upgrade to upgrade): netCDF4 in /usr/local/lib/python2.7/dist-packages (from dummydata)
    Downloading/unpacking dateutil (from dummydata)
      Could not find any downloads that satisfy the requirement dateutil (from dummydata)
    Cleaning up...
    No distributions at all found for dateutil (from dummydata)
    Storing debug log for failure in /tmp/tmpDapV7h

Option 2: Conda - package not found

    Fetching package metadata .........
    Solving package specifications: .
    PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
      - dummydata

    You can search for packages on anaconda.org with

        anaconda search -t conda dummydata

Follow up: anaconda search: - 0 packages

Option 3: GIT - Could not find suitable distribution

    ....
    Processing dependencies for dummydata==0.1.2 
    Searching for dateutil
    Reading https://pypi.python.org/simple/dateutil/
    No local packages or working download links found for dateutil
    error: Could not find suitable distribution for Requirement.parse('dateutil')

**Comment by bulli92** [comment]
Problems with Option 1 and Option 3 should be (hopefully) fixed now.
I modified the setup.py dependencies and created a new PyPi version (v0.1.3). This should work, please test.

regarding Option 2, you did the installation wrong! Please read the doc here, which specifies that the `conda-forge` channel needs to be used. Thus I guess your command needs to look something like so

> anaconda search -c conda-forge dummy data

**Comment by bulli92** [comment]
please note that conda based installation can not work yet, as the package is not yet on the conda-forge server. PR still pending there.

**Comment by BenMGeo** [comment]
Had to uninstall dummydata and install it back again. *pip freeze* shows *dummydata==0.1.3*.

It is installed in:

    /usr/local/lib/python2.7/dist-packages

Fine so far.

Though, in python I cannot import it, while *sys.path* shows exactly the same directory.

**Comment by bulli92** [comment]
I guess this is due to the fact that you use conda as default! This is always troublesome when combining PIP and conda.

The solution is as follows:
1) install the conda version of PIP
```
conda install pip
```

2) after that install the package you want using pip, but make sure that the conda version of pip is used. The easiest way to ensure that is if you work in a specific virtual environment anyway.
```
pip install dummydata
```
This should then install the `dummy data`package in a `site-package`directory within the `conda` installation and **not** within `/usr/local/...`

I guess this should solve the problem.

**Comment by bulli92** [comment]
close this now, as PIP installation. is working using travis.yml
